spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wysiwyg
    username: root
    password: windows12796@

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true