spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wysiwyg
    username: root
    password: windows12796@

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  jackson:
    default-property-inclusion: non_null

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 8c04a9c42b1e115638ac
            clientSecret: 0b22417531acba341e94b6a65ef9c87267b0f191
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user

app:
  upload:
    dir: D:/dev/what-you-see-is-what-you-get/backend/server/src/main/resources/images/

  auth:
    tokenSecret: WYSIWYG
    tokenExpirationMsec: 86400000

  oauth2:
    authorizedRedirectUris:
      - http://localhost:5000/oauth2/redirect
