spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wysiwyg
    username: root
    password: windows12796@

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

app:
  upload:
    dir: D:/dev/what-you-see-is-what-you-get/backend/server/src/main/resources/images
